stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - params.yaml
    outs:
      - data/raw/twitter_training.csv

  data_validation:
    cmd: python src/data/data_validation.py
    deps:
      - src/data/data_validation.py
      - data/raw/twitter_training.csv
      - params.yaml
    outs:
      - reports/validation_report.json

  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - src/data/data_cleaning.py
      - data/raw/twitter_training.csv
    outs:
      - data/interim/cleaned_data.csv
  
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/interim/cleaned_data.csv
      - params.yaml
    outs:
      - data/processed
      - models/artifacts

  model_training:
    cmd: python src/model/model_training.py
    deps:
      - src/model/model_training.py
      - data/processed
      - models/artifacts
      - params.yaml
    outs:
      - models/lgbm_model.pkl
      - reports/experiment.json   # ONLY HERE

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - data/processed
      - models/lgbm_model.pkl
      - models/artifacts
      - params.yaml
      - reports/experiment.json 
    outs:
      - reports/classification_report.json
      - reports/confusion_matrix.png

  model_registry:
    cmd: python src/model/model_registry.py
    deps:
      - src/model/model_registry.py
      - reports/experiment.json  